version: '3.4'

services:
  dsrnetschool_api:
    image: dsrnetschoolapi:dev
    container_name: DSRNetSchool.Api
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "DSRNetSchool.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_dsrnetschool_api$
    volumes:
      - F:\DSR\myproject\Systems\Api\DSRNetSchool.Api:/app
      - F:\DSR\myproject:/src
      - C:\Users\TBOTB\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_dsrnetschool_api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_dsrnetschool_api$ \"/app/bin/Debug/net7.0/DSRNetSchool.Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  dsrnetschool_identity:
    image: dsrnetschoolidentity:dev
    container_name: DSRNetSchool.Identity
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "DSRNetSchool.Identity"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_dsrnetschool_identity$
    volumes:
      - F:\DSR\myproject\Systems\Identity\DSRNetSchool.Identity:/app
      - F:\DSR\myproject:/src
      - C:\Users\TBOTB\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_dsrnetschool_identity$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_dsrnetschool_identity$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  dsrnetschool_worker_1:
    image: dsrnetschoolworker:dev
    container_name: DSRNetSchool.Worker
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "DSRNetSchool.Worker"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_dsrnetschool_worker_1$
    volumes:
      - F:\DSR\myproject\Systems\Workers\DSRNetSchool.Worker:/app
      - F:\DSR\myproject:/src
      - C:\Users\TBOTB\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_dsrnetschool_worker_1$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_dsrnetschool_worker_1$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  dsrnetschool_worker_2:
    image: dsrnetschoolworker:dev
    container_name: DSRNetSchool.Worker_1
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "DSRNetSchool.Worker"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_dsrnetschool_worker_2$
    volumes:
      - F:\DSR\myproject\Systems\Workers\DSRNetSchool.Worker:/app
      - F:\DSR\myproject:/src
      - C:\Users\TBOTB\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_dsrnetschool_worker_2$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_dsrnetschool_worker_2$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
